# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 161a713aa31732c9668c40670b9cea8435c6c4da7a80be7955615657e6ba2232f6f3ff93ba8d851ca694ff756ed89102d27b368c4ca2ead5f6b342f208ce15f3

test:
  secret_key_base: 027d2f25e69cefc8a949813a3e2bf89256437ca1d102be836ea20ce2a296ed695b1e1f74b685003ffbd0c4f0b3b67443e69eee87a3267a9b2ae4e53e68367d87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
